name: PrivateStatus
description: Hides your server status from unknown players.
version: "${project.version}-${git.commit.id.describe}"
api-version: "1.20"
main: me.tinyoverflow.privatestatus.PrivateStatus