#file: noinspection SpellCheckingInspection
name: Build and Publish

on:
  push:
    tags: [ "*.*" ]
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "pom.xml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: 'temurin'
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Attach Plugin File to Action Run
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: |
            target/privatestatus*.jar
            CHANGELOG.md

      - name: Publish to GitHub Packages Apache Maven
        run: mvn --batch-mode deploy -s $GITHUB_WORKSPACE/settings.xml
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}

  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve Plugin File from Action Run
        uses: actions/download-artifact@v3
        with:
          name: plugin

      - name: Publish to Distribution Platforms
        uses: Kir-Antipov/mc-publish@v3.3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          version: ${{ github.ref_name }}
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: paper
          game-versions: ">=1.20"
          java: 17

          files: "privatestatus*.jar"

          github-tag: ${{ github.ref_name }}
          github-token: ${{ github.token }}

          modrinth-id: 15lfFvuG
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}