name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "*.*" ]
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "pom.xml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Attach Plugin File to Action Run
        uses: actions/upload-artifact@v3
        with:
          path: target/PrivateStatus*.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/PrivateStatus*.jar
